# Blog description
title: Araz Abishov
email: araz.abishov.gsoc@gmail.com
description: >
  Writing about android development, open source and some other important
  stuff.

# Blog configuration
baseurl: ""
url: "https://abishov.com" # the base hostname & protocol for your site
twitter_username: arazabishov
github_username:  arazabishov

# Build settings
markdown: kramdown
theme: minima
