# Blog description
title: Araz Abishov
email: araz.abishov.gsoc@gmail.com
description: >
  Bits and bytes of open source, android development and some
  other exciting stuff.

# Blog configuration
url: ""
twitter_username: arazabishov
github_username:  arazabishov

# Build settings
markdown: kramdown
theme: minima

# Disqus configuration
disqus:
  shortname: abishov

# Analytics
google_analytics: UA-83806464-1
