# Blog description
title: Araz Abishov
email: araz@abishov.com
description: >
  Bits and bytes about open source, Android and Rust.

# Blog configuration
url: https://abishov.com
twitter_username: arazabishov
github_username:  arazabishov

# Build settings
markdown: kramdown
theme: minima

# Disqus configuration
disqus:
  shortname: abishov

# Analytics
google_analytics: UA-163945772-1
