# Blog description
title: Araz Abishov
email: araz.abishov.gsoc@gmail.com
description: >
  Writing about android development, open source and some other important
  stuff.

# Blog configuration
url: https://abishov.com
twitter_username: arazabishov
github_username:  arazabishov

# Build settings
markdown: kramdown
theme: minima
