# Blog description
title: Araz Abishov
email: araz@abishov.com
description: >
  Bits and bytes about open source, Android and Rust.

# Blog configuration
url: https://abishov.com
twitter_username: arazabishov
github_username:  arazabishov

# Build settings
markdown: kramdown

plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima@3cdd14dff1216f561c68329e0b7420c2dc9b796a

minima:
  skin: dark

# Disqus configuration
disqus:
  shortname: abishov

# Analytics
google_analytics: G-069EDE29TP
